#encoding:utf-8
# define router tag values
module PageObject
		#####################login ############################
		@@ts_tag_login_usr          = 'admuser'
		@@ts_tag_login_pw           = 'admpass'
		@@usr_text_id               = 'admuser'
		@@ts_tag_usr                = @@usr_text_id
		@@pw_text_id                = 'admpass'
		@@ts_tag_pw                 = @@pw_text_id
		@@login_button              = '登录'
		@@ts_tag_login_btn          = @@login_button
		@@usr                       = "admin"
		@@ts_default_usr            = @@usr
		@@pw                        = "admin"
		@@ts_default_pw             = @@pw
		##########################net set#######################
		@@ts_tag_netset             = "set_network"
		@@ts_tag_netset_src         = "netset.asp"
		@@ts_tag_mode               = "apmode"
		######wan mode
		@@ts_wan_mode_dhcp          = "DHCP"
		@@ts_wan_mode_pppoe         = "PPPOE"
		@@ts_wan_mode_pptp          = "PPTP"
		@@ts_wan_mode_static        = "STATIC"
		@@ts_wan_mode_repeater      = "Repeater"
		@@ts_wan_mode_bridge        = "Bridge"
		@@ts_wan_mode_3g_4g         = "3G/4G"
		@@ts_tag_wired_mode_link    = "tab_ip"
		@@ts_tag_wired_mode_span    = "wire"
		@@ts_wireless_id            = "wireless"
		@@ts_tag_wired_dhcp         = "ip_type_dhcp"
		@@ts_tag_wired_pppoe        = "ip_type_pppoe"
		@@ts_tag_wired_static       = "ip_type_static"
		@@ts_tag_pppoe_usr          = "pppoeUser"
		@@ts_tag_pppoe_pw           = "input_password1"
		@@ts_tag_wired_static       = "ip_type_static"
		@@ts_tag_3g_mode_link       = "tab_3g"
		@@ts_tag_3g_mode_span       = "dial"
		@@ts_tag_3g_auto            = "3g_auto_type"
		@@ts_wired_static_id        = "wire-static"
		@@ts_wired_static_ip        = "staticIp"
		@@ts_wired_static_err       = "error_msg"
		@@ts_tag_wan_err            = "error_msg"
		######################## static ip  ############
		@@ts_tag_staticIp           = "staticIp"
		@@ts_tag_staticNetmask      = "staticNetmask"
		@@ts_tag_staticGateway      = "staticGateway"
		@@ts_tag_staticPriDns       = "staticPriDns"
		@@ts_tag_backupDns          = "backupDns"
		########lan set ######
		@@ts_tag_lan                = "set_wifi"
		@@ts_tag_lan_src            = "lanset.asp"
		@@ts_tag_lanip              = "lan_ip"
		@@ts_tag_lanstart           = "dhcpStart"
		@@ts_tag_lanend             = "dhcpEnd"
		@@ts_tag_lanerr             = "error_msg"
		@@ts_lanip_err              = "DHCP地址格式有误"
		@@ts_default_leasetime      = "43200"
		@@ts_ssid_test_pre          = "ZhiluAuto"
		@@ts_tag_ssid               = "ssid"
		@@ts_tag_ssid_pwd           = "input_password1"
		@@ts_tag_sec_select_list    = "security_mode"
		@@ts_sec_mode_none          = 'None'
		@@ts_sec_mode_none_cn       = "无加密"
		@@ts_sec_mode_wpa           = 'WPA-PSK/WPA2-PSK'
		@@ts_tag_input_pw           = "input_password1"
		@@ts_tag_dhcp_lease         = "dhcpLease"
		@@ts_tag_systemver          = "sysversion"
		@@ts_tag_sys_ver            = "系统版本"
		@@ts_lan_mask               = "255.255.255.0"
		@@ts_default_wlan_pw        = "12345678"
		@@ts_tag_reboot_confirm     = "aui_state_highlight"
		@@ts_tag_reboot_cancel      = "取消"
		######reboot####
		@@ts_tag_del_ipfilter_btn   = "all_del"
		###system######
		@@ts_tag_account_manage     = "passwd.asp"
		@@ts_tag_modify_pw          = "system_config"
		@@ts_tag_aduser             = "admuser"
		@@ts_tag_adpass             = "admpass"
		@@ts_tag_adpass2            = "admpass2"
		@@ts_tag_modify_pw_error    = "error_msg"
		@@ts_tag_logout             = "logout"
		@@ts_tag_login_error        = "error_text"
		################  ap  #################
		@@ts_tag_ap_src             = "d_wizard_step1_start.asp"
		@@ts_tag_ap_save            = "save"
		@@ts_dut_ssid               = "WIRELESS-SSID"
		@@ts_channel                = "WIRELESS-CH"
		@@ts_pwdshow2               = "pwdshow2"
		@@ts_pwdshow                = "pwdshow"
		@@ts_ap_save_hint           = "loading"
		@@ts_ap_safe_option         = "methodSel"
		@@ts_ap_status              = "d_status.asp"
		@@ts_ap_maintain            = "d_reboot.asp"
		@@ts_ap_maintain_reboot     = "reboot"
		@@ts_main_content           = "maincontent"
		@@ts_ap_setting             = "d_wizard_step1_start.asp"
		@@ts_ap_wireless            = "d_wlan_basic.asp"
		@@ts_wifi_advanced_setup    = "d_wladvanced.asp"
		@@ts_24G_wifi_switch        = "advWlanDisabled"
		@@ts_ap_login_btn           = "loginBtn"
		@@ts_ap_wireless_pattern    = "band"
		@@ts_ap_channel             = "chan"
		@@ts_ap_bandwidth           = "chanwid"
		@@ts_ap_save_hint           = "loading"
		@@ts_bridge_id              = "mode-bridge"
		@@ts_dut_wifi_ssid          = "wifi"
		@@ts_dut_wifi_ssid_pwd      = "skey1"
		@@ts_manual_step_name       = "wizardstep1_back"
		@@ts_ap_wan_type            = "wantype"
		@@ts_ap_ip_addr_static      = "staip_ipaddr"
		@@ts_ap_mask_static         = "staip_netmask"
		@@ts_ap_gateway_static      = "staip_gateway"
		@@ts_ap_dns1_static         = "wan_dns1"
		@@ts_ap_ver_info            = "top_product"
		############### dut内网 ################
		@@ts_wifi_switch            = "wifiswitch"
		############### dut外网 ################
		@@ts_relay_id               = "mode-relay"
		@@ts_search_net             = "ssid_reflash"
		@@ts_ssid_list              = "ssid_list"
		@@ts_net_pwd                = "input_password3"
		############### dut状态 ################
		@@ts_wifi_status            = "WIRELESS-ONOFF"
		############### dut高级设置 ############
		@@ts_advance_setup          = "WIFI-Settings"
		@@ts_wifi_channel           = "sz11gChannel"
		############### dut url ################
		@@ts_url_set                = "menu_set"
		@@ts_url_black              = "b_w_select"
		@@ts_web_url                = "b_w_url"
		@@ts_tag_url_text_black     = "black"
		@@ts_tag_url_text_white     = "white"
		@@ts_tag_url_type_black     = "黑名单"
		@@ts_tag_url_type_white     = "白名单"
		############### dut ip #################
		@@ts_ip_set                 = "IP-Filter"
		@@ts_ip_src                 = "fip"
		@@ts_ip_src_end             = "endip"
		@@ts_ip_err                 = "error_msg"
		@@ts_ip_dst                 = "gip"
		@@ts_ip_dst_end             = "gendip"
		@@ts_ip_start_time          = "starttime"
		@@ts_ip_end_time            = "endtime"
		@@ts_ip_start_time1         = "starttime1"
		@@ts_ip_end_time1           = "endtime1"
		@@ts_ip_invalid             = "all_invalid"
		@@ts_ip_valid               = "all_valid"
		@@ts_ip_dst_port            = "gport"
		@@ts_ip_dst_port_end        = "gendport"
		@@ts_ip_dst_port1           = "gport1"
		@@ts_ip_dst_port_end1       = "gendport1"
		@@ts_ip_src_port            = "fport"
		@@ts_ip_src_port_end        = "endport"
		@@ts_ip_src_port1           = "fport1"
		@@ts_ip_src_port_end1       = "endport1"
		@@ts_iptable                = "iptable"
		@@ts_ip_hint_close          = "aui_close"
		@@ts_tag_aui_close          = "aui_close"
		@@ts_tag_aui_clsignal       = "×"
		@@ts_tag_aui_titbar         = "aui_titleBar"
		############### dut 系统状态 ################
		@@ts_sys_status             = "systatus"
		@@ts_sys_status_src         = "systatus.asp"
		@@ts_pro_version_id         = "version"
		@@ts_software_version_id    = "software-version"
		@@ts_terminal_num_id        = "terminal-num"
		############## dut 定时 #####################
		@@ts_tag_plan_task          = "plantask-titile"
		@@ts_btn_id                 = "switch"
		@@ts_timing_strategy        = "strategy"
		@@ts_taday_id               = "laydate_today"
		@@ts_time_classname         = "laydate_sj"
		@@ts_time_minute            = "laydate_hmsno"
		@@ts_time_ok                = "laydate_ok"
		@@ts_tag_clear_time         = "laydate_clear"
		@@ts_rebot_btn              = "baocun"
		@@ts_rebot_time             = "reboottime"
		@@ts_tag_router_time        = "routetime"
		@@ts_tag_restart_strategy   = "strategy"
		@@ts_select_time_id         = "date_first"
		@@ts_today_id               = "laydate_today"
		################ 设备连接列表 #############
		@@ts_tag_customtag          = "zl"
		@@ts_tag_custom_id          = "terminalnum2"
		@@ts_tag_devices_iframe_src = "dhcpclient.asp"
		@@ts_device_list_id         = "device_list"
		@@ts_device_list_cls_name   = "routers-table"
		@@ts_tag_devlist            = "dev_ico"
		@@ts_tag_devlist_refresh    = "refresh-btn"
		@@ts_tag_devlist_table      = "device_list"
		################# option tags #########################
		@@ts_tag_options            = "options"
		@@ts_tag_advance_src        = "pptp.asp"
		@@ts_tag_apoption_src       = "update.asp"
		@@ts_tag_filename           = "filename"
		@@ts_tag_inport_btn         = "update_submit_btn"
		@@ts_tag_err_msg            = "error_msg"
		#reboot
		@@ts_tag_op_reboot          = "reboot_submit_btn"
		@@ts_tag_op_reboot_tab      = "reboot-titile"
		@@ts_tag_op_system          = "syssetting"
		@@ts_select_time_name       = "starttime"
		@@ts_tag_select_state       = "selected"
		@@ts_tag_recover            = "reset-titile"
		@@ts_tag_reset_factory      = "reset_submit_btn"
		@@ts_tag_export             = "setmanExpSetExport"
		@@ts_default_config_name    = "RT2880_Settings.dat"
		@@ts_tag_syslog             = "syslog-titile"
		@@ts_tag_liclass            = "active"
		@@ts_tag_logclear           = "syslogSysLogClear"
		@@ts_tag_log_textarea       = "syslog"
		@@ts_update                 = "update-titile"
		@@ts_update_brower          = "brower"
		@@ts_update_filename        = "filename"
		@@ts_tag_update_btn         = "update_submit_btn"
		@@ts_reset_default_fname    = "filename"
		@@ts_tag_domain             = "device"
		@@ts_tag_domain_field       = "domain"
		@@ts_tag_domain_name        = "domain_name"
		@@ts_tag_domain_err         = "error_msg"
		@@ts_tag_virsrvip_err       = "error_msg"
		######文件共享
		@@ts_tag_fileshare          = "USB-titile"
		@@ts_tag_fileshare_btn_type = "button"
		@@ts_tag_filebtn_off        = "off"
		@@ts_tag_filebtn_on         = "on"
		@@ts_file_share_dir         = "Folder_structure.asp"
		@@ts_storage_usb            = "U盘"
		@@ts_storage_sd             = "SD卡"
		@@ts_tag_disshare           = "disshare"
		@@ts_tag_close_share        = "关闭共享"
		@@ts_tag_return             = "return"
		@@ts_tag_back               = "返回上一级"
		@@ts_tag_catalog_first      = "一级目录"
		@@ts_tag_udisk_seconddir    = "二级目录"
		@@ts_tag_udisk_dir_en       = "first_dir"
		@@ts_tag_udisk_file1        = "一级测试文件_TEST.txt"
		@@ts_tag_udisk_file2        = "一级安卓软件_TEST.apk"
		@@ts_tag_udisk_file3        = "一级安卓软件.apk"
		@@ts_tag_udisk_file4        = "first_anzuo.apk"
		@@ts_tag_second_testfile    = "二级测试文件_TEST.txt"
		@@ts_tag_cur_path           = "cur_path"
		@@ts_tag_sec_py_testfile    = "二级Pycharm_TEST.exe"
		@@ts_tag_sec_ruby_testfile  = "二级RubyMine_TEST.exe"
		@@ts_tag_udisk_thr_file     = "三级安卓软件.apk"
		#######应用设置
		####dmz
		@@ts_tag_application        = "aplicationsetting"
		@@ts_tag_dmz                = "dmzSetting"
		@@ts_tag_dmzsw              = "switch"
		@@ts_tag_dmzip              = "dwz_ip"
		@@ts_tag_dmzsw_on           = "on"
		@@ts_tag_dmzsw_off          = "off"
		@@ts_conn_state             = "succeed"
		@@ts_tag_ddns               = "ddnsSetting"
		@@ts_tag_ddns_sw            = "switch"
		@@ts_tag_ddns_host          = "host"
		@@ts_tag_ddns_user          = "user"
		@@ts_tag_ddns_pwd           = "pwd"
		@@ts_tag_ddns_save          = "savebtn"
		#####虚拟服务器
		@@ts_tag_virtualsrv_sw      = "switch"
		@@ts_tag_virtualsrv         = "virtualServer"
		@@ts_tag_virsw_on           = "on"
		@@ts_tag_virsw_off          = "off"
		@@ts_tag_addvir             = "add_btn"
		@@ts_tag_virip1             = "ip0"
		@@ts_tag_virpub_port1       = "port0"
		@@ts_tag_virpri_port1       = "port1"
		@@ts_tag_virip2             = "ip1"
		@@ts_tag_virpub_port2       = "port2"
		@@ts_tag_virpri_port2       = "port3"
		@@ts_tag_virip3             = "ip2"
		@@ts_tag_virpub_port3       = "port4"
		@@ts_tag_virpri_port3       = "port5"
		@@ts_tag_virip4             = "ip3"
		@@ts_tag_virpub_port4       = "port6"
		@@ts_tag_virpri_port4       = "port7"
		@@ts_tag_virip5             = "ip4"
		@@ts_tag_virpub_port5       = "port8"
		@@ts_tag_virpri_port5       = "port9"
		@@ts_tag_virip6             = "ip5"
		@@ts_tag_virpub_port6       = "port10"
		@@ts_tag_virpri_port6       = "port11"
		@@ts_tag_vir_protocol       = "protocol1"
		@@ts_tag_vir_status         = "status1"
		@@ts_tag_vir_protocol1      = "protocol"
		@@ts_tag_vir_status1        = "status"
		@@ts_tag_delvir             = "delete_btn"
		@@ts_tag_save_btn           = "take_effect_btn"
		#####防火墙
		@@ts_tag_security           = "securitysetting"
		@@ts_tag_fwset              = "Firewall-Settings"
		@@ts_tag_security_sw        = "switch1"
		@@ts_tag_security_url       = "switch4"
		@@ts_tag_security_mac       = "switch3"
		@@ts_tag_security_ip        = "switch2"
		@@ts_tag_security_save      = "save_btn"
		@@ts_tag_macfilter          = "MAC-Filter"
		@@ts_tag_fwstatus           = "firewall"
		@@ts_tag_fwmac              = "macgl"
		@@ts_tag_fw_open            = "开启"
		@@ts_tag_fw_close           = "关闭"
		@@ts_tag_additem            = "additem"
		@@ts_tag_alladd             = "alladd"
		@@ts_tag_allcancel          = "allcancle"
		@@ts_tag_alldel             = "alldel"
		@@ts_tag_fwmac_mac          = "mac"
		@@ts_tag_fwmac_desc         = "desc"
		@@ts_tag_fw_select          = "status"
		@@ts_tag_fwmac_mac1         = "mac1"
		@@ts_tag_fwmac_desc1        = "desc1"
		@@ts_tag_fw_select1         = "status1"
		@@ts_tag_save_filter        = "save_btniptb"
		@@ts_tag_save_filter1       = "save_btniptb1"
		@@ts_tag_filter_use         = "生效"
		@@ts_tag_filter_nouse       = "失效"
		@@ts_tag_mac_table          = "macguolv"
		@@ts_tag_del                = "del"
		@@ts_tag_edit               = "edit"
		@@ts_tag_ip_back            = "back_ip"
		@@ts_tag_mac_table          = "macfilter_table"
		@@ts_tag_edit_mac           = "edit_mac"
		@@ts_tag_mac_display        = "tab3"
		####remote web access
		@@ts_tag_op_remote          = "webtoroute"
		@@ts_tag_op_web_accbtn      = "on-off"
		@@ts_remote_default_port    = "9000"
		@@ts_remote_sw              = "on-off"
		@@ts_remote_port_id         = "port"
		@@ts_remote_port_name       = "port"
		@@ts_remote_save_btn        = "submit_btn"
		####networking pptp
		@@ts_tag_op_network         = "networksetting"
		@@ts_tag_op_pptp            = "PPTP-Settings"
		@@ts_tag_pptp_server        = "lanIp"
		@@ts_tag_pptp_usr           = "username"
		@@ts_tag_pptp_pw            = "psd"
		@@ts_pptp_server_ip         = "10.10.10.1"
		@@ts_pptp_usr               = "pptp"
		@@ts_pptp_pw                = "pptp"
		####bandwidth
		@@ts_tag_bandwidth          = "traffic-titile"
		@@ts_tag_traffic            = "traffic-contol"
		@@ts_tag_bandsw             = "wideband_limiter"
		@@ts_tag_wideband           = "wideband_size"
		@@ts_tag_range_min          = "ip_range_min_0"
		@@ts_tag_range_max          = "ip_range_max_0"
		@@ts_tag_band_mode          = "wideband_mode_0"

		@@ts_tag_range_min2 = "ip_range_min_1"
		@@ts_tag_range_max2 = "ip_range_max_1"
		@@ts_tag_band_mode2 = "wideband_mode_1"

		@@ts_tag_range_min3 = "ip_range_min_2"
		@@ts_tag_range_max3 = "ip_range_max_2"
		@@ts_tag_band_mode3 = "wideband_mode_2"

		@@ts_tag_range_min4 = "ip_range_min_3"
		@@ts_tag_range_max4 = "ip_range_max_3"
		@@ts_tag_band_mode4 = "wideband_mode_3"

		@@ts_tag_range_min5        = "ip_range_min_4"
		@@ts_tag_range_max5        = "ip_range_max_4"
		@@ts_tag_band_mode5        = "wideband_mode_4"
		@@ts_tag_bandlimit         = "受限最大带宽"
		@@ts_tag_bandensure        = "保障最小带宽"
		@@ts_tag_band_size         = "wideband_size_0"
		@@ts_tag_client_bandsw     = "on_off_net_0"
		@@ts_tag_band_size2        = "wideband_size_1"
		@@ts_tag_client_bandsw2    = "on_off_net_1"
		@@ts_tag_band_size3        = "wideband_size_2"
		@@ts_tag_client_bandsw3    = "on_off_net_2"
		@@ts_tag_band_size4        = "wideband_size_3"
		@@ts_tag_client_bandsw4    = "on_off_net_3"
		@@ts_tag_band_size5        = "wideband_size_4"
		@@ts_tag_client_bandsw5    = "on_off_net_4"
		@@ts_tag_band_tb           = "table_box"
		@@ts_tag_band_err          = "error_msg"
		######################status Tags#############################################
		@@tag_status_iframe_src    = "setstatus.asp"
		@@ts_tag_status_iframe_src = @@tag_status_iframe_src
		@@ts_tag_status            = "setstatus"
		@@ts_tag_lan_ip            = "LAN-IP"
		@@tag_wan_ip               = "WAN-IP"
		@@ts_tag_wan_ip            = @@tag_wan_ip
		@@tag_wan_type             = "WAN-CONTYPE"
		@@ts_tag_wan_type          = @@tag_wan_type
		@@tag_wan_dns              = "WAN-DNS"
		@@ts_tag_wan_dns           = @@tag_wan_dns
		@@tag_wan_mask             = "WAN-NETMASK"
		@@ts_tag_wan_mask          = @@tag_wan_mask
		@@tag_wan_gw               = "WAN-GATEWAY"
		@@ts_tag_wan_gw            = @@tag_wan_gw
		@@ts_tag_lan_mac           = "LAN-MAC"

		@@ts_tag_sbm            = "submit_btn"
		@@ts_tag_reboot         = "reboottxt"
		###########新版本3/4状态与原来版本差异很大 3/4G ################
		# 3G/4G拨号状态
		@@ts_tag_diag_status    = "dial-status"
		@@ts_tag_diag_text      = "3G/4G拨号状态"
		# SIM卡状态
		@@ts_tag_sim            = "sim"
		@@ts_tag_sim_status     = "sim_status"
		@@ts_tag_img_normal     = "images/d.png"
		# 信号强度29
		@@ts_tag_signal         = "xinhao"
		@@ts_tag_signal_strenth = "wifi-signal"
		@@ts_tag_signal_normal  = "images/5.png"
		# 注册状态
		@@ts_tag_reg            = "reg"
		@@ts_tag_reg_status     = "register-status"
		# 联网状态
		@@ts_tag_3g_net         = "lianwang"
		@@ts_tag_3g_net_status  = "net_status"
		# 网络类型4G
		@@ts_tag_3g_nettype     = "nettype"
		@@ts_tag_3g_net_type    = "net_type"
		@@ts_tag_4g_nettype_text= "4G"
		# 运营商名称CHINA MOBILE
		@@ts_tag_3g_isp         = "yiname"
		@@ts_tag_3g_ispname     = "net_name"
		@@ts_tag_3g_ispname_text= "CHINA MOBILE"
		#################################diagnose tags#######################
		@@ts_tag_diagnose       = "net_detect"
		@@ts_tag_ad_diagnose    = "advanced-diagnosis"
		@@ts_tag_url            = "url"
		@@ts_tag_diag_btn       = "btnDet"
		@@ts_tag_diag_detect    = "route-detect"
		@@ts_tag_diag_success   = "正常"
		@@ts_tag_diag_fail      = "异常"

		@@ts_tag_diag_3gdial          = "3gdial"
		@@tc_tag_diag_3gdial_text     = "3G拨号状态"
		@@ts_tag_diag_3gdial_status   = "checking"
		@@ts_tag_diag_wan             = "network-conn"
		@@ts_tag_diag_wan_text        = "WAN口连接状态"
		@@ts_tag_diag_wan_status      = "checking1"
		@@ts_tag_wan_class            = "detail"
		@@ts_tag_diag_internet        = "wlan-conn"
		@@ts_tag_diag_internet_text   = "外网连接状态"
		@@ts_tag_diag_internet_status = "checking2"
		@@ts_tag_diag_hardware        = "hardware-status"
		@@ts_tag_diag_hardware_text   = "路由硬件状态"
		@@ts_tag_diag_hardware_status = "checking4"
		@@ts_tag_diag_netspeed        = "network-speed"
		@@ts_tag_diag_netspeed_text   = "连接速度状态"
		@@ts_tag_diag_netspeed_status = "checking3"

		@@ts_tag_diag_cpu       = "cpu"
		@@ts_tag_diag_cpu_text  = "处理器信息"
		@@ts_tag_diag_cpu_xpath = "/html/body/div[2]/div[5]/div[2]"
		@@ts_tag_cpu_type_reg   = /处理器类型：.+/im
		@@ts_tag_cpu_name_reg   = /处理器型号：.+/im
		@@ts_tag_cpu_load_reg   = /系统负载：\d+\.\d+/im

		@@ts_tag_diag_mem       = "ram"
		@@ts_tag_diag_mem_text  = "内存信息"
		@@ts_tag_diag_mem_xpath = "/html/body/div[2]/div[6]/div[2]"
		@@ts_tag_mem_total_reg  = /内存总量\s*：\s*[1-9]+\d*\s*M/m
		@@ts_tag_mem_useful_reg = /可用内存\s*：\s*[1-9]+\d*\s*M/m
		@@ts_tag_mem_cache_reg  = /缓存内存\s*：\s*[1-9]+\d*\s*M/m

		# Wanprotocal （上网连接类型）：DHCP
		@@ts_tag_diag_nettype   = "Wanprotocal （上网连接类型）："
		# Wanlink （Wan连接状态）：正常
		@@ts_tag_net_status     = "Wanlink （Wan连接状态）："
		# IP （域名解析到的IP地址）：180.97.33.108
		@@ts_tag_domain_ip      = "IP （域名解析到的IP地址）："
		@@ts_domina_ip_fail     = "失败"
		# GW （连接默认网关的丢包率）：0%
		@@ts_tag_loss           = "GW （连接默认网关的丢包率）："
		# DNS （解析域名）：成功
		@@ts_tag_dns            = "DNS （解析域名）："
		# HTTP （域名状态码）：200
		@@ts_tag_http_status    = "HTTP （域名状态码）："

		@@ts_net_link              = "正常"
		@@ts_net_link_fail         = "失败"
		@@ts_ip_reg                = /[1-9]\d{0,2}\.\d{1,3}\.\d{1,3}\.[1-9]\d{0,2}/
		@@ts_loss_rate             = "0%"
		@@ts_loss_rate_all         = "100%"
		@@ts_dns_status            = "成功"
		@@ts_dns_status_fail       = "失败"
		@@ts_http_status           = "200"
		@@ts_http_status_fail      = "404"
		################### mac clone ######################
		@@ts_tag_clone_mac         = "MAC-Clone"
		@@ts_tag_clone_sw          = "switch"
		@@ts_tag_fillmac           = "fillmac"
		@@ts_tag_pcmac             = "pc_mac"
		@@ts_tag_errormsg          = "error_msg"
		@@ts_cap_timeout           = 15
		@@ts_server_lannic         = "LAN"
		@@ts_tag_btn_off           = "off"
		@@ts_tag_btn_on            = "on"
		############################### other ####################################
		##ftp
		@@ts_ftp_usr               = "admin"
		@@ts_ftp_pw                = "admin"
		@@ts_ff_profile            = "default"
		############### 2016/01/04###################
		@@ts_tag_wlan_link         = "tab_sta"
		@@ts_tag_repeater_radio    = "imodel_type_zj"
		@@ts_tag_bridge_radio      = "imodel_type_qj"
		@@ts_tag_ap_ssid           = "ssid"
		@@ts_tag_ap_aes            = "WPA-PSK/WPA2-PSK AES"
		@@ts_ap_pw                 = "zhilutest"
		@@ts_tag_ap_pw             = "pskValue"
		@@ts_nicname_three         = "three"
		################### 2016/01/07 llp ###########
		@@ts_tag_ap_ssid_name      = "ssid"
		@@ts_tag_ap_ssid_pwd       = "pskValue"
		@@ts_unified_platform_user = "root"
		@@ts_unified_platform_pwd  = "zl4321"
		@@ts_tag_refresh_btn       = "refresh-btn"
		@@ts_tag_ip_filter_state   = "ipgl"
		@@ts_tag_export_name       = "ExportSet"
		@@ts_tag_wan_mac           = "WAN-MAC"
		@@ts_tag_wifi              = "setstatus"
		@@ts_tag_status_form       = "status"
		@@ts_tag_status_table1     = "body_header"
		@@ts_tag_status_table2     = "formlisting"

		#sys status
		@@ts_tag_verinfo           = "version-info"
		@@ts_tag_waninfo           = "WAN-status"
		@@ts_tag_laninfo           = "LAN-status"
		@@ts_tag_lanmask           = "lanNetmask"
		@@ts_tag_sysprotype        = "product-mode"
		@@ts_tag_sysruntime        = "running-time"
		@@ts_tag_sysprover         = "version"
		@@ts_tag_syspromac         = "product-mac"
		@@ts_tag_systerminal       = "terminal-num"

		@@ts_tag_syssoftver = "software-version"
		@@ts_tag_syshardver = "hardware-version"

		@@ts_tag_syssimstatus = "sim"
		@@ts_tag_syssignal    = "xinhao"

		@@ts_tag_sysreg       = "reg"
		@@ts_tag_sysconnstatus= "lianwang"
		@@ts_tag_sysconntype  = "nettype"
		@@ts_tag_sysispname   = "yiname"

		@@ts_tag_syswan     = "link_type_wan"
		@@ts_tag_syswanmac  = "WAN-MAC"
		@@ts_tag_syswanip   = "WAN-IP"
		@@ts_tag_syswanmask = "WAN-NETMASK"
		@@ts_tag_syswangw   = "WAN-GATEWAY"
		@@ts_tag_syswandns  = "WAN-DNS"

		@@ts_tag_syslanmac        = "LAN-MAC"
		@@ts_tag_syslanip         = "LAN-IP"
		@@ts_tag_syslanmask       = "LAN-NETMASK"

		#wan
		@@ts_tag_syswifistatus    = "WIRELESS-status"
		@@ts_tag_syswifisw        = "wifiswitch"
		@@ts_tag_syswifisw_5g     = "WIRELESS_hard"
		@@ts_tag_syswifisw_status = "WIRELESS-ONOFF2G"
		@@ts_tag_sys_ssid         = "WIRELESS-SSID2G"
		@@ts_tag_syschanel        = "WIRELESS-2GCH"
		@@ts_tag_syschanel_5g     = "WIRELESS-5GCH"
		@@ts_tag_sysencry         = "WIRELESS-ENCRY"
		@@ts_tag_wifi_details     = "wifi_details"

		@@ts_tag_mode_iframe        = "modeselect.asp"
		@@ts_tag_apmode             = "imodel_type_ap"
		@@ts_tag_routermode         = "imodel_type_rt"
		@@ts_tag_showpwd            = "pwdshow_skey"
		@@ts_tag_3g_hand_type       = "3g_hand_type"
		@@ts_tag_cancel             = "close_box"
		@@ts_wire_mode_tab_cls_name = "radio_network_type selected"
		@@ts_tag_3g_handtype_apn    = "APN3G"
		@@ts_tag_3g_handtype_pin    = "PIN3G"
		@@ts_tag_3g_handtype_num    = "Dial3G"
		@@ts_tag_3g_handtype_user   = "User3G"
		@@ts_tag_3g_handtype_pwd    = "Password3G"

		#wifi
		@@ts_tag_wifiset            = "setwifi.asp"
		@@ts_tag_wifi_basic         = "tab_basal"
		@@ts_tag_radio_basic        = "ip_type_b_2g"
		@@ts_tag_radio_basic_5g     = "ip_type_b_5g"
		@@ts_tag_radio_adv          = "ip_type_a_2g"
		@@ts_tag_radio_adv_5g       = "ip_type_a_5g"
		#wifi ssid
		@@ts_tag_wifi_ssid1         = "2g_ssid_name0"
		@@ts_tag_wifi_ssid2         = "2g_ssid_name1"
		@@ts_tag_wifi_ssid3         = "2g_ssid_name2"
		@@ts_tag_wifi_ssid4         = "2g_ssid_name3"
		@@ts_tag_wifi_ssid5         = "2g_ssid_name4"
		@@ts_tag_wifi_ssid6         = "2g_ssid_name5"
		@@ts_tag_wifi_ssid7         = "2g_ssid_name6"
		@@ts_tag_wifi_ssid8         = "2g_ssid_name7"
		#wifi ssid 5G
		@@ts_tag_wifi_ssid1_5g      = "5g_ssid_name0"
		@@ts_tag_wifi_ssid2_5g      = "5g_ssid_name1"
		@@ts_tag_wifi_ssid3_5g      = "5g_ssid_name2"
		@@ts_tag_wifi_ssid4_5g      = "5g_ssid_name3"
		@@ts_tag_wifi_ssid5_5g      = "5g_ssid_name4"
		@@ts_tag_wifi_ssid6_5g      = "5g_ssid_name5"
		@@ts_tag_wifi_ssid7_5g      = "5g_ssid_name6"
		@@ts_tag_wifi_ssid8_5g      = "5g_ssid_name7"
		#wifi pw
		@@ts_tag_wifi_pw1           = "2g_passwd_data0"
		@@ts_tag_wifi_pw2           = "2g_passwd_data1"
		@@ts_tag_wifi_pw3           = "2g_passwd_data2"
		@@ts_tag_wifi_pw4           = "2g_passwd_data3"
		@@ts_tag_wifi_pw5           = "2g_passwd_data4"
		@@ts_tag_wifi_pw6           = "2g_passwd_data5"
		@@ts_tag_wifi_pw7           = "2g_passwd_data6"
		@@ts_tag_wifi_pw8           = "2g_passwd_data7"
		#wifi pw 5G
		@@ts_tag_wifi_pw1_5g        = "5g_passwd_data0"
		@@ts_tag_wifi_pw2_5g        = "5g_passwd_data1"
		@@ts_tag_wifi_pw3_5g        = "5g_passwd_data2"
		@@ts_tag_wifi_pw4_5g        = "5g_passwd_data3"
		@@ts_tag_wifi_pw5_5g        = "5g_passwd_data4"
		@@ts_tag_wifi_pw6_5g        = "5g_passwd_data5"
		@@ts_tag_wifi_pw7_5g        = "5g_passwd_data6"
		@@ts_tag_wifi_pw8_5g        = "5g_passwd_data7"
		#wifi link
		@@ts_tag_wifi_linknum1      = "2g_max_link0"
		@@ts_tag_wifi_linknum2      = "2g_max_link1"
		@@ts_tag_wifi_linknum3      = "2g_max_link2"
		@@ts_tag_wifi_linknum4      = "2g_max_link3"
		@@ts_tag_wifi_linknum5      = "2g_max_link4"
		@@ts_tag_wifi_linknum6      = "2g_max_link5"
		@@ts_tag_wifi_linknum7      = "2g_max_link6"
		@@ts_tag_wifi_linknum8      = "2g_max_link7"
		#wifi link 5G
		@@ts_tag_wifi_linknum1_5g   = "5g_max_link0"
		@@ts_tag_wifi_linknum2_5g   = "5g_max_link1"
		@@ts_tag_wifi_linknum3_5g   = "5g_max_link2"
		@@ts_tag_wifi_linknum4_5g   = "5g_max_link3"
		@@ts_tag_wifi_linknum5_5g   = "5g_max_link4"
		@@ts_tag_wifi_linknum6_5g   = "5g_max_link5"
		@@ts_tag_wifi_linknum7_5g   = "5g_max_link6"
		@@ts_tag_wifi_linknum8_5g   = "5g_max_link7"
		#wifi pwmode
		@@ts_tag_pw_mode1           = "2g_passwd_mode0"
		@@ts_tag_pw_mode2           = "2g_passwd_mode1"
		@@ts_tag_pw_mode3           = "2g_passwd_mode2"
		@@ts_tag_pw_mode4           = "2g_passwd_mode3"
		@@ts_tag_pw_mode5           = "2g_passwd_mode4"
		@@ts_tag_pw_mode6           = "2g_passwd_mode5"
		@@ts_tag_pw_mode7           = "2g_passwd_mode6"
		@@ts_tag_pw_mode8           = "2g_passwd_mode7"
		#wifi pwmode 5G
		@@ts_tag_pw_mode1_5g        = "5g_passwd_mode0"
		@@ts_tag_pw_mode2_5g        = "5g_passwd_mode1"
		@@ts_tag_pw_mode3_5g        = "5g_passwd_mode2"
		@@ts_tag_pw_mode4_5g        = "5g_passwd_mode3"
		@@ts_tag_pw_mode5_5g        = "5g_passwd_mode4"
		@@ts_tag_pw_mode6_5g        = "5g_passwd_mode5"
		@@ts_tag_pw_mode7_5g        = "5g_passwd_mode6"
		@@ts_tag_pw_mode8_5g        = "5g_passwd_mode7"
		#wiif sw
		@@ts_tag_wifi_sw1           = "2g_wifi_switch0"
		@@ts_tag_wifi_sw2           = "2g_wifi_switch1"
		@@ts_tag_wifi_sw3           = "2g_wifi_switch2"
		@@ts_tag_wifi_sw4           = "2g_wifi_switch3"
		@@ts_tag_wifi_sw5           = "2g_wifi_switch4"
		@@ts_tag_wifi_sw6           = "2g_wifi_switch5"
		@@ts_tag_wifi_sw7           = "2g_wifi_switch6"
		@@ts_tag_wifi_sw8           = "2g_wifi_switch7"
		#wiif sw 5G
		@@ts_tag_wifi_sw1_5g        = "5g_wifi_switch0"
		@@ts_tag_wifi_sw2_5g        = "5g_wifi_switch1"
		@@ts_tag_wifi_sw3_5g        = "5g_wifi_switch2"
		@@ts_tag_wifi_sw4_5g        = "5g_wifi_switch3"
		@@ts_tag_wifi_sw5_5g        = "5g_wifi_switch4"
		@@ts_tag_wifi_sw6_5g        = "5g_wifi_switch5"
		@@ts_tag_wifi_sw7_5g        = "5g_wifi_switch6"
		@@ts_tag_wifi_sw8_5g        = "5g_wifi_switch7"

		@@ts_tag_wifi_advance   = "tab_advance"
		@@ts_tag_wifi_switch    = "wifi_2g_switch"
		@@ts_tag_wifi_switch_5g = "wifi_5g_switch" #5g
		@@ts_tag_rsi            = "rssi_2g"
		@@ts_tag_rsi_5g         = "rssi_5g" #5g
		@@ts_tag_wifichannel    = "sz_2g_Channel"
		@@ts_tag_wifichannel_5g = "sz_5g_Channel" #5g
		@@ts_tag_wifiopen       = "OPEN"
		#lan
		@@ts_tag_ipstart        = "ip_start"
		@@ts_tag_ipend          = "ip_end"
		@@ts_tag_advance_new    = "pptp.asp"
		#vps
		@@ts_tag_delete_vps1    = "//*[@id='table1']/tbody/tr[2]/td[7]/a"
		@@ts_tag_delete_vps2    = "//*[@id='table1']/tbody/tr[3]/td[7]/a"
		@@ts_tag_delete_vps3    = "//*[@id='table1']/tbody/tr[4]/td[7]/a"
		@@ts_tag_delete_vps4    = "//*[@id='table1']/tbody/tr[5]/td[7]/a"
		@@ts_tag_delete_vps5    = "//*[@id='table1']/tbody/tr[6]/td[7]/a"
		@@ts_tag_delete_vps6    = "//*[@id='table1']/tbody/tr[7]/td[7]/a"

		@@ts_tag_dhcp_btn         = "button"
		@@ts_tag_aui_content      = "aui_content"
		@@ts_tag_aui_content_text = "超出限制"
		#mac clone
		@@ts_tag_mac_clone        = "mac_clone"
		#system
		@@ts_tag_filename_new     = "filename"
		#wifidetail
		@@ts_tag_wifidetail_src   = "wifidetails.asp"
		@@ts_tag_wifitable        = "table1"
		@@ts_tag_ssid1            = "ssid_name0"
		@@ts_tag_ssid2            = "ssid_name1"
		@@ts_tag_ssid3            = "ssid_name2"
		@@ts_tag_ssid4            = "ssid_name3"
		@@ts_tag_ssid5            = "ssid_name4"
		@@ts_tag_ssid6            = "ssid_name5"
		@@ts_tag_ssid7            = "ssid_name6"
		@@ts_tag_ssid8            = "ssid_name7"
		@@ts_tag_ssid9            = "ssid_name8"
		@@ts_tag_ssid10           = "ssid_name9"
		@@ts_tag_ssid11           = "ssid_name10"
		@@ts_tag_ssid12           = "ssid_name11"
		@@ts_tag_ssid13           = "ssid_name12"
		@@ts_tag_ssid14           = "ssid_name13"
		@@ts_tag_ssid15           = "ssid_name14"
		@@ts_tag_ssid16           = "ssid_name15"
		@@ts_tag_ssid1_pwmode     = "passwd_mode0"
		@@ts_tag_ssid2_pwmode     = "passwd_mode1"
		@@ts_tag_ssid3_pwmode     = "passwd_mode2"
		@@ts_tag_ssid4_pwmode     = "passwd_mode3"
		@@ts_tag_ssid5_pwmode     = "passwd_mode4"
		@@ts_tag_ssid6_pwmode     = "passwd_mode5"
		@@ts_tag_ssid7_pwmode     = "passwd_mode6"
		@@ts_tag_ssid8_pwmode     = "passwd_mode7"
		@@ts_tag_ssid9_pwmode     = "passwd_mode8"
		@@ts_tag_ssid10_pwmode    = "passwd_mode9"
		@@ts_tag_ssid11_pwmode    = "passwd_mode10"
		@@ts_tag_ssid12_pwmode    = "passwd_mode11"
		@@ts_tag_ssid13_pwmode    = "passwd_mode12"
		@@ts_tag_ssid14_pwmode    = "passwd_mode13"
		@@ts_tag_ssid15_pwmode    = "passwd_mode14"
		@@ts_tag_ssid16_pwmode    = "passwd_mode15"
		@@ts_tag_ssid1_linknum    = "max_link0"
		@@ts_tag_ssid2_linknum    = "max_link1"
		@@ts_tag_ssid3_linknum    = "max_link2"
		@@ts_tag_ssid4_linknum    = "max_link3"
		@@ts_tag_ssid5_linknum    = "max_link4"
		@@ts_tag_ssid6_linknum    = "max_link5"
		@@ts_tag_ssid7_linknum    = "max_link6"
		@@ts_tag_ssid8_linknum    = "max_link7"
		@@ts_tag_ssid9_linknum    = "max_link8"
		@@ts_tag_ssid10_linknum   = "max_link9"
		@@ts_tag_ssid11_linknum   = "max_link10"
		@@ts_tag_ssid12_linknum   = "max_link11"
		@@ts_tag_ssid13_linknum   = "max_link12"
		@@ts_tag_ssid14_linknum   = "max_link13"
		@@ts_tag_ssid15_linknum   = "max_link14"
		@@ts_tag_ssid16_linknum   = "max_link15"
		@@ts_tag_ssid1_linked     = "linked0"
		@@ts_tag_ssid2_linked     = "linked1"
		@@ts_tag_ssid3_linked     = "linked2"
		@@ts_tag_ssid4_linked     = "linked3"
		@@ts_tag_ssid5_linked     = "linked4"
		@@ts_tag_ssid6_linked     = "linked5"
		@@ts_tag_ssid7_linked     = "linked6"
		@@ts_tag_ssid8_linked     = "linked7"
		@@ts_tag_ssid9_linked     = "linked8"
		@@ts_tag_ssid10_linked    = "linked9"
		@@ts_tag_ssid11_linked    = "linked10"
		@@ts_tag_ssid12_linked    = "linked11"
		@@ts_tag_ssid13_linked    = "linked12"
		@@ts_tag_ssid14_linked    = "linked13"
		@@ts_tag_ssid15_linked    = "linked14"
		@@ts_tag_ssid16_linked    = "linked15"
		@@ts_tag_ssid1_rf         = "rf_card0"
		@@ts_tag_ssid2_rf         = "rf_card1"
		@@ts_tag_ssid3_rf         = "rf_card2"
		@@ts_tag_ssid4_rf         = "rf_card3"
		@@ts_tag_ssid5_rf         = "rf_card4"
		@@ts_tag_ssid6_rf         = "rf_card5"
		@@ts_tag_ssid7_rf         = "rf_card6"
		@@ts_tag_ssid8_rf         = "rf_card7"
		@@ts_tag_ssid9_rf         = "rf_card8"
		@@ts_tag_ssid10_rf        = "rf_card9"
		@@ts_tag_ssid11_rf        = "rf_card10"
		@@ts_tag_ssid12_rf        = "rf_card11"
		@@ts_tag_ssid13_rf        = "rf_card12"
		@@ts_tag_ssid14_rf        = "rf_card13"
		@@ts_tag_ssid15_rf        = "rf_card14"
		@@ts_tag_ssid16_rf        = "rf_card15"
		@@ts_tag_ssid1_sw         = "wifi_switch0"
		@@ts_tag_ssid2_sw         = "wifi_switch1"
		@@ts_tag_ssid3_sw         = "wifi_switch2"
		@@ts_tag_ssid4_sw         = "wifi_switch3"
		@@ts_tag_ssid5_sw         = "wifi_switch4"
		@@ts_tag_ssid6_sw         = "wifi_switch5"
		@@ts_tag_ssid7_sw         = "wifi_switch6"
		@@ts_tag_ssid8_sw         = "wifi_switch7"
		@@ts_tag_ssid9_sw         = "wifi_switch8"
		@@ts_tag_ssid10_sw        = "wifi_switch9"
		@@ts_tag_ssid11_sw        = "wifi_switch10"
		@@ts_tag_ssid12_sw        = "wifi_switch11"
		@@ts_tag_ssid13_sw        = "wifi_switch12"
		@@ts_tag_ssid14_sw        = "wifi_switch13"
		@@ts_tag_ssid15_sw        = "wifi_switch14"
		@@ts_tag_ssid16_sw        = "wifi_switch15"
		#wizard
		@@ts_tag_rediag           = "rediagnosis"
		@@ts_tag_ad_diagnose_err  = "mod-result"
		@@ts_tag_guide            = "setup_guide"
		@@ts_tag_step0            = "images/step1.png"
		@@ts_tag_map0             = "Map0"
		@@ts_tag_step1            = "images/step2.png"
		@@ts_tag_map1             = "Map1"
		@@ts_tag_step2            = "images/step3.png"
		@@ts_tag_map2             = "Map2"
		@@ts_tag_step3            = "images/step4.png"
		@@ts_tag_map3             = "Map3"
		@@ts_tag_step4            = "images/step5.png"
		@@ts_tag_map4             = "Map4"
		@@ts_tag_update_box       ="update_box"
end
